InsightHub/InsightHub.Web/Controllers/ReportsController.cs
using InsightHub.Services.Contracts;
using InsightHub.Services.DTOs;
using InsightHub.Services.DTOs.TagDTOs;
using InsightHub.Services.IndustryDTOs.DTOs;
using InsightHub.Services.Providers.Contracts;
using InsightHub.Services.ReportDTOs.DTOs;
using InsightHub.Web.Models.IndustryApiViewModels;
using InsightHub.Web.Models.ReportsMVCViewModels;
using InsightHub.Web.Models.TagApiViewModels;
using InsightHub.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace InsightHub.Web.Controllers
{
    /// <summary>
    ///MVC Controller for the Report service that:
    ///   - Displays all reports in the index page
    ///    - Displays detailed information for reports in the details page
    ///     - Displays action to create a report in the create page
    ///      - Displays functionality to download reports attached file
    ///       -  Displays all user downloaded reports in MyDownloads page
    ///        -  Displays all user reports in MyReports page
    ///         -  Displays featured reports in the Home page
    ///          - Displays action to edit a report
    ///           - Displays action to delete a report
    /// </summary>
    public class ReportsController : Controller
    {
        private readonly IReportService _reportService;
        private readonly IIndustryServices _industryServices;
        private readonly ITagServices _tagServices;
        private readonly IUserService _userService;
        private readonly IFileTypeProvider _fileTypeProvider;

        public ReportsController(IReportService reportService, IIndustryServices industryServices,
            ITagServices tagServices, IUserService userService, IFileTypeProvider fileTypeProvider)
        {
            _reportService = reportService;
            _industryServices = industryServices;
            _tagServices = tagServices;
            _userService = userService;
            _fileTypeProvider = fileTypeProvider;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            var reportsDTO = await _reportService.GetAllReportsAsync();

            var reportsView = reportsDTO.Select(report => new ReportsIndexMVCViewModel
            {
                ReportID = report.ReportID,
                ReportName = report.ReportName,
                Description = report.Description,
                Author = new UserIndexViewModel
                { UserID = report.AuthorID, FullName = $"{report.Author.FirstName} {report.Author.LastName}", Email = report.Author.Email},
                AuthorID = report.AuthorID,
                Industry = new IndustryApiViewModel 
                {IndustryID = report.Industry.IndustryID, IndustryName = report.Industry.IndustryName },
                ReportTags = report.ReportTags.Select(tag => new TagApiViewModel 
                {TagID = tag.TagID, TagName = tag.TagName }).ToList(),
                IsFeatured = report.IsFeatured
            });

            return View(reportsView);
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            try
            {
                var reportDTO = await _reportService.GetReportAsync(id);

                var reportViewModel = new ReportDetailsMVCViewModel
                {
                    ReportID = reportDTO.ReportID,
                    ReportName = reportDTO.ReportName,
                    Description = reportDTO.Description,
                    Author = new UserIndexViewModel
                    {
                        UserID = reportDTO.AuthorID,
                        FullName = $"{reportDTO.Author.FirstName} {reportDTO.Author.LastName}",
                        Email = reportDTO.Author.Email
                    },
                    Industry = new IndustryApiViewModel
                    { IndustryID = reportDTO.Industry.IndustryID, IndustryName = reportDTO.Industry.IndustryName },
                    ReportTags = reportDTO.ReportTags.Select(tag => new TagApiViewModel
                    { TagID = tag.TagID, TagName = tag.TagName }).ToList(),
                    FileTitle = reportDTO.FileTitle,
                    CreatedOn = reportDTO.CreatedOn,
                    DownloadCount = reportDTO.DownloadCount
                };

                return View(reportViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [Authorize(Roles ="Author, Admin")]        
        public async Task<IActionResult> Create()
        {           
            ViewData["TagName"] = new SelectList(await _tagServices.GetAllTagsAsync(), "TagName", "TagName");
            ViewData["IndustryName"] = new SelectList(await _industryServices.GetAllIndustriesAsync(), "IndustryID", "IndustryName");
            ReportCreateMVCViewModel newReport = new ReportCreateMVCViewModel();
            return View(newReport);
        }

        [Authorize(Roles = "Author, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
        [FromForm] ReportCreateMVCViewModel report)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userID = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);

                if (report.File.Length > 25*1024*1024)
                {
                    return RedirectToAction(nameof(Create));
                }

                    var reportDTO = new ReportCreateDTO
                    {
                        ReportID = report.ReportID,
                        ReportName = report.ReportName,
                        Description = report.Description,
                        Author = new UserDTO
                        { UserID = userID },
                        Industry = new IndustryCreateDTO
                        { IndustryID = report.IndustryID },
                        ReportTags = report.Tags.Select(tag => new TagNameDTO
                        { TagName = tag }).ToList(),
                        File = report.File
                    };

                    await _reportService.CreateReportAsync(reportDTO);
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Create));
            }
            catch(InvalidOperationException)
            {
                return BadRequest();
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        [Authorize]
        public async Task<IActionResult> DownloadFile(Guid reportID)
        {
            try
            {
                var userID = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);
                var report = await this._reportService.GetReportAsync(reportID);
                if (report == null)
                {
                    return BadRequest();
                }
                var memory = await this._reportService.DownloadReportAsync(reportID, userID);

                var ext = _fileTypeProvider.GetFileType(report.FileTitle);

                return File(memory, ext, report.FileTitle);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        [Authorize]
        public IActionResult DownloadFileUnauthenticated(Guid reportID)
        {
            return RedirectToAction(nameof(Details), new { id = reportID });            
        }

        [Authorize]
        public async Task<IActionResult> MyDownloads()
        {
            try
            {
                var userID = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);

                var downloads = await this._reportService.GetMyDownloadsAsync(userID);

                if (downloads == null)
                {
                    return View();
                }

                var userDownloads = downloads.Select(dr => new ReportMyDownloadsMVCViewModel
                {
                    ReportID = dr.ReportID,
                    ReportName = dr.Report.ReportName,
                    Description = dr.Report.Description,
                    FileTitle = dr.Report.FileTitle
                });

                return View(userDownloads);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
        [Authorize]
        public async Task<IActionResult> MyReports()
        {
            try
            {
                var userID = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);

                var myReports = await this._reportService.GetMyReportsAsync(userID);

                if (myReports == null)
                {
                    return View();
                }

                var userDownloads = myReports.Select(r => new ReportMyDownloadsMVCViewModel
                {
                    ReportID = r.ReportID,
                    ReportName = r.ReportName,
                    Description = r.Description,
                    FileTitle = r.FileTitle
                });

                return View(userDownloads);
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DownloadFileForApproval(Guid id)
        {
            try
            {
                var userID = int.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value);
                var report = await this._reportService.GetReportForApprovalAsync(id);

InsightHub/InsightHub.Web/Controllers/UsersController.cs
using InsightHub.Services.Contracts;
using InsightHub.Web.Models;
using InsightHub.Web.Models.ReportsMVCViewModels;
using InsightHub.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace InsightHub.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        /// <summary>
        ///MVC Controller for the User service that:
        ///   - Displays all users in the index page
        ///    - Displays detailed information for user in the details page
        ///     - Displays action to delete a report in the delete page
        ///      - Displays functionality to approve/reject pending reports
        ///       - Displays functionality to approve/reject new user accounts
        /// </summary>
        private readonly IUserService _userService;
        private readonly IReportService _reportService;

        public UsersController(IUserService userService, IReportService reportService)
        {
            _userService = userService;
            _reportService = reportService;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAllUsers();

            var usersVM = users.Select(user => new UserIndexViewModel
            {
                UserID = user.UserID,
                FullName = $"{user.FirstName} {user.LastName}",
                Email = user.Email,
                IsApprovedByAdmin = user.IsApprovedByAdmin,
                HasPendingReports = user.HasPendingReports,
                IsBanned = user.IsBanned
            });

            return View(usersVM);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var user = await _userService.GetUserAsync(id);

                var userVM = new UserIndexViewModel { UserID = user.UserID, FullName = $"{user.FirstName} {user.LastName}", Email = user.Email };

                return View(userVM);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var user = await _userService.GetUserAsync(id);

                var userVM = new UserIndexViewModel
                {
                    UserID = user.UserID,
                    FullName = $"{user.FirstName} {user.LastName}",
                    Email = user.Email,
                    IsApprovedByAdmin = user.IsApprovedByAdmin,
                    HasPendingReports = user.HasPendingReports
                };

                return View(userVM);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var isUserDeleted = await _userService.DeleteUserAsync(id);

            if(!isUserDeleted)
            {
                return NotFound();
            }
           
            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> PendingApprovals()
        {
            var usersPendingApproval = await _userService.GetAllPendingApprovalUsers();
            var reportsPendingApproval = await _userService.GetAllPendingApprovalReports();

            var apprVM = new ApprovalsModel
            {
                PendingUsers = usersPendingApproval.Select(user => new UserIndexViewModel
                {
                    UserID = user.UserID,
                    FullName = $"{user.FirstName} {user.LastName}",
                    Email = user.Email

                }).ToList(),
                PendingReports = reportsPendingApproval.Select(rep => new ReportsIndexMVCViewModel
                {
                    ReportID = rep.ReportID,
                    ReportName = rep.ReportName,
                    AuthorID = rep.AuthorID,
                    Author = new UserIndexViewModel { Email = rep.Author.Email }
                }).ToList()
            };           

            return View("Approvals", apprVM);
        }
        
        public async Task<IActionResult> ApprovalConfirmed(int id)
        {
            var isUserApproved = await _userService.ApproveUserAsync(id);

            if(!isUserApproved)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }       

        public async Task<IActionResult> ApprovalReportConfirmed(Guid id)
        {
            var isReportApproved = await _userService.ApproveReport(id);

            if (!isReportApproved)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }

        public async Task<IActionResult> RejectUserRegistration(int id)
        {
            var isRegistrationRejected = await _userService.DeleteUserAsync(id);

            if(!isRegistrationRejected)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }

        public async Task<IActionResult> RejectReport(Guid id)
        {
            var isReportRejected = await _reportService.DeleteReportAsync(id);

            if(!isReportRejected)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }
        
        public async Task<IActionResult> Ban(int id)
        {
            try
            {
                var isBanned = await _userService.BanUserAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Unban(int id)
        {
            try
            {
                var isUnbaned = await _userService.UnbanUserAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }
    }
}

InsightHub/InsightHub.Web/Views/Users/Approvals.cshtml
@model InsightHub.Web.Models.ApprovalsModel

@{
    ViewData["Title"] = "Approvals";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Registration Approvals</h1>

<p>
    @await Html.PartialAsync("PendingApprovalUsers", Model.PendingUsers)
    <br />
    @await Html.PartialAsync("PendingApprovalReports", Model.PendingReports)
</p>

InsightHub/InsightHub.Web/Views/Users/Delete.cshtml
@model InsightHub.Web.Models.UserViewModels.UserIndexViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this user?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InsightHub/InsightHub.Web/Views/Users/Details.cshtml
@model InsightHub.Web.Models.UserViewModels.UserIndexViewModel;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        
    </dl>
</div>
<div>   
    <a asp-action="Index">Back to List</a>
</div>

InsightHub/InsightHub.Web/Views/Users/Index.cshtml
@model IEnumerable<InsightHub.Web.Models.UserViewModels.UserIndexViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        /* Margin bottom by footer height */
        background-image: url('../img/videoblocks-blue-business-background-2_h3cvzluwb_thumbnail-full01.png');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-size: cover;
    }
</style>

<h1>Index</h1>

<table id="users" class="table-striped table-bordered" style="width: 100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => user.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.Email)
                </td>

            @if (User.IsInRole("Admin") && User.Identity.Name == user.Email)
            {
                <td>ADMIN</td>
            }
            else
            {
        <td>
            @Html.ActionLink("Details", "Details", "Users", new { id = user.UserID }, new { @class = "btn btn-outline-success" })
            @Html.ActionLink("Delete", "Delete", "Users", new { id = user.UserID }, new { @class = "btn btn-outline-danger" })
            @if (user.IsBanned)
            {
                @Html.ActionLink("Unban", "Unban", "Users", new { id = user.UserID }, new { @class = "btn btn-outline-success" })
            }
            else
            {
                @Html.ActionLink("Ban", "Ban", "Users", new { id = user.UserID }, new { @class = "btn btn-outline-danger" })
            }
            @if (!user.IsApprovedByAdmin || user.HasPendingReports)
            {
                @Html.ActionLink("Pending Approvals", "PendingApprovals", "Users", new { id = user.UserID }, new { @class = "btn btn-danger flash btn-custom" })
            }
        </td>
            }
        </tr>
}
    </tbody>
</table>

InsightHub/InsightHub.Web/Views/Users/PendingApprovalReports.cshtml
@model ICollection<InsightHub.Web.Models.ReportsMVCViewModels.ReportsIndexMVCViewModel>

<h1>Report Approvals</h1>

@if (!Model.Any())
{
    <strong>No pending report approvals currently!</strong>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().ReportName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Author.Email)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var report in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => report.ReportName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => report.Author.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Approve", "ApprovalReportConfirmed", "Users", new { id = report.ReportID }, new { @class = "btn btn-outline-success" })
                        @Html.ActionLink("Reject", "RejectReport", "Users", new { id = report.ReportID }, new { @class = "btn btn-outline-danger" })
                        @Html.ActionLink("Download", "DownloadFileForApproval", "Reports", new { id = report.ReportID }, new { @class = "btn btn-outline-primary" })
                    </td>
                </tr>

            }
        </tbody>
    </table>
}

InsightHub/InsightHub.Web/Views/Users/PendingApprovalUsers.cshtml
@model ICollection<InsightHub.Web.Models.UserViewModels.UserIndexViewModel>

@if (!Model.Any())
{
    <strong>No pending registration approvals currently!</strong>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => Model.First().FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => Model.First().Email)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => user.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => user.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Approve", "ApprovalConfirmed", "Users", new { id = user.UserID }, new { @class = "btn btn-outline-success" })
                        @Html.ActionLink("Reject", "RejectUserRegistration", "Users", new { id = user.UserID }, new { @class = "btn btn-outline-danger" })
                    </td>
                </tr>
            }

        </tbody>
    </table>

}