InsightHub/InsightHub.Web/Controllers/TagsController.cs
using InsightHub.Services.Contracts;
using InsightHub.Services.DTOs;
using InsightHub.Web.Models.ReportApiViewModels;
using InsightHub.Web.Models.TagApiViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InsightHub.Web.Controllers
{
    public class TagsController : Controller
    {
        /// <summary>
        ///MVC Controller for the Tag service that:
        ///   - Displays all tags in the index page
        ///    - Displays detailed information for tag in the details page
        ///     - Displays action to create an tag in the create page
        ///      - Displays action to edit a tag in the edit page
        ///       - Displays action to delete a tag in the delete page
        ///          
        /// </summary>
        private readonly ITagServices _tagServices;

        public TagsController(ITagServices tagServices)
        {
            _tagServices = tagServices;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
            var tags = await _tagServices.GetAllTagsAsync();

            var tagViewModels = tags.Select(tag => new TagApiDetailsViewModel
            {
                TagID = tag.TagID,
                TagName = tag.TagName,
                TagReports = tag.TagReports.Select(report => new ReportNameDescrViewModel
                { ReportID = report.ReportID, ReportName = report.Report.ReportName, Description = report.Report.Description }).ToList()
            });

            return View(tagViewModels);
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var tag = await _tagServices.GetTagAsync(id);

                var tagViewModels = new TagApiDetailsViewModel
                {
                    TagID = tag.TagID,
                    TagName = tag.TagName,
                    TagReports = tag.TagReports.Select(report => new ReportNameDescrViewModel
                    { ReportID = report.ReportID, ReportName = report.Report.ReportName, Description = report.Report.Description }).ToList()
                };

                if (tag == null)
                {
                    return NotFound();
                }

                return View(tagViewModels);
            }
            catch(Exception)
            {
                return NotFound();
            }
        }

        // GET: Tags/Create
        [Authorize(Roles = "Author, Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Author, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TagApiInputModel tag)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _tagServices.CreateTagAsync(tag.TagName);

                    return View();
                }
                return View(tag.TagName);
            }
            catch (Exception)
            {
                return BadRequest();
            }

        }

        // GET: Tags/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var tag = await _tagServices.GetTagAsync(id);

                var tagViewModels = new TagApiViewModel
                { TagID = tag.TagID, TagName = tag.TagName };

                if (tag == null)
                {
                    return NotFound();
                }
                return View(tagViewModels);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TagID,TagName")] TagApiViewModel tag)
        {
            if (id != tag.TagID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var tagDTO = new TagDTO { TagID = tag.TagID, TagName = tag.TagName };

                    await _tagServices.UpdateTagAsync(tagDTO);
                }
                catch (Exception)
                {
                    if (!await TagExists(tag.TagID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        return BadRequest();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var tag = await _tagServices.GetTagAsync(id);

                var tagViewModels = new TagApiDetailsViewModel
                {
                    TagID = tag.TagID,
                    TagName = tag.TagName,
                    TagReports = tag.TagReports.Select(report => new ReportNameDescrViewModel
                    { ReportID = report.ReportID, ReportName = report.Report.ReportName, Description = report.Report.Description }).ToList()
                };

                return View(tagViewModels);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        // POST: Tags/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var tag = await _tagServices.DeleteTagAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        private async Task<bool> TagExists(int id)
        {
            try
            {
                var tag = await _tagServices.GetTagAsync(id);

                return true;
            }
            catch (ArgumentNullException)
            {
                return false;
            }
        }
    }
}

InsightHub/InsightHub.Web/Controllers/UsersController.cs
using InsightHub.Services.Contracts;
using InsightHub.Web.Models;
using InsightHub.Web.Models.ReportsMVCViewModels;
using InsightHub.Web.Models.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace InsightHub.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        /// <summary>
        ///MVC Controller for the User service that:
        ///   - Displays all users in the index page
        ///    - Displays detailed information for user in the details page
        ///     - Displays action to delete a report in the delete page
        ///      - Displays functionality to approve/reject pending reports
        ///       - Displays functionality to approve/reject new user accounts
        /// </summary>
        private readonly IUserService _userService;
        private readonly IReportService _reportService;

        public UsersController(IUserService userService, IReportService reportService)
        {
            _userService = userService;
            _reportService = reportService;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAllUsers();

            var usersVM = users.Select(user => new UserIndexViewModel
            {
                UserID = user.UserID,
                FullName = $"{user.FirstName} {user.LastName}",
                Email = user.Email,
                IsApprovedByAdmin = user.IsApprovedByAdmin,
                HasPendingReports = user.HasPendingReports,
                IsBanned = user.IsBanned
            });

            return View(usersVM);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var user = await _userService.GetUserAsync(id);

                var userVM = new UserIndexViewModel { UserID = user.UserID, FullName = $"{user.FirstName} {user.LastName}", Email = user.Email };

                return View(userVM);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var user = await _userService.GetUserAsync(id);

                var userVM = new UserIndexViewModel
                {
                    UserID = user.UserID,
                    FullName = $"{user.FirstName} {user.LastName}",
                    Email = user.Email,
                    IsApprovedByAdmin = user.IsApprovedByAdmin,
                    HasPendingReports = user.HasPendingReports
                };

                return View(userVM);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var isUserDeleted = await _userService.DeleteUserAsync(id);

            if(!isUserDeleted)
            {
                return NotFound();
            }
           
            return RedirectToAction(nameof(Index));
        }
        
        public async Task<IActionResult> PendingApprovals()
        {
            var usersPendingApproval = await _userService.GetAllPendingApprovalUsers();
            var reportsPendingApproval = await _userService.GetAllPendingApprovalReports();

            var apprVM = new ApprovalsModel
            {
                PendingUsers = usersPendingApproval.Select(user => new UserIndexViewModel
                {
                    UserID = user.UserID,
                    FullName = $"{user.FirstName} {user.LastName}",
                    Email = user.Email

                }).ToList(),
                PendingReports = reportsPendingApproval.Select(rep => new ReportsIndexMVCViewModel
                {
                    ReportID = rep.ReportID,
                    ReportName = rep.ReportName,
                    AuthorID = rep.AuthorID,
                    Author = new UserIndexViewModel { Email = rep.Author.Email }
                }).ToList()
            };           

            return View("Approvals", apprVM);
        }
        
        public async Task<IActionResult> ApprovalConfirmed(int id)
        {
            var isUserApproved = await _userService.ApproveUserAsync(id);

            if(!isUserApproved)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }       

        public async Task<IActionResult> ApprovalReportConfirmed(Guid id)
        {
            var isReportApproved = await _userService.ApproveReport(id);

            if (!isReportApproved)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }

        public async Task<IActionResult> RejectUserRegistration(int id)
        {
            var isRegistrationRejected = await _userService.DeleteUserAsync(id);

            if(!isRegistrationRejected)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }

        public async Task<IActionResult> RejectReport(Guid id)
        {
            var isReportRejected = await _reportService.DeleteReportAsync(id);

            if(!isReportRejected)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(PendingApprovals));
        }
        
        public async Task<IActionResult> Ban(int id)
        {
            try
            {
                var isBanned = await _userService.BanUserAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Unban(int id)
        {
            try
            {
                var isUnbaned = await _userService.UnbanUserAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }
    }
}

InsightHub/InsightHub.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InsightHub.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://fontawesome.com/icons/adobe?style=brands"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script> 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InsightHub</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
                        <div class="dropdown-menu">
                            @if ((User.IsInRole("Admin")) || (User.IsInRole("Author")))
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Reports" asp-action="Create">Create New</a>
                            }
                            <a class="dropdown-item" asp-area="" asp-controller="Reports" asp-action="Index">All Reports</a>
                            @if ((User.IsInRole("Admin")) || (User.IsInRole("Author")))
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Reports" asp-action="MyReports">My Reports</a>
                            }
                            @if ((User.IsInRole("Admin")) || (User.IsInRole("Author")) || (User.IsInRole("Customer")))
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Reports" asp-action="MyDownloads">My Downloads</a>
                            }
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Tags</a>
                        <div class="dropdown-menu">
                            @if ((User.IsInRole("Admin")) || (User.IsInRole("Author")))
                            {
                            <a class="dropdown-item" asp-area="" asp-controller="Tags" asp-action="Create">Create New</a>
                            }
                            <a class="dropdown-item" asp-area="" asp-controller="Tags" asp-action="Index">All Tags</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Industries</a>
                        <div class="dropdown-menu">
                            @if ((User.IsInRole("Admin")))
                            {
                            <a class="dropdown-item" asp-area="" asp-controller="Industries" asp-action="Create">Create New</a>
                            }
                            <a class="dropdown-item" asp-area="" asp-controller="Industries" asp-action="Index">All Industries</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="PendingApprovals">Approvals</a>
                            </div>
                        }
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top-0 footer text-muted">
        <div class="container">
            @*&copy; 2020 - InsightHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                <br>*@
            InsightHub - Api - <a href="http://localhost:60972/swagger/index.html" class="btn-custom">Develop</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script type="text/javascript" src="~/lib/datatables.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>